#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#1366x768
#yif [[ $(xrandr -q | grep 'VGA1 connected') ]]; then
xrandr --output VGA1 --primary --mode 800x600 --rotate normal
#xrandr --output LVDS1 --primary --mode 1366x868 --rotate normal --output VGA1 --mode 1024x768 --right-of LVDS1
#bspc monitor LVDS1 -d 1 2 3
#bspc monitor VGA1 -d 4 5 6 7
#fi

bspc monitor LVDS1 -d 1 2 3 4 5 6 7

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xsetroot -cursor_name left_ptr
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
